config/routes.rb
BillBadger::Application.routes.draw do

  get "static_pages/about"
  
  get "static_pages/home"

  resources :transactions

  resources :users

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  attr_accessible :value, :from_user_id, :to_user_id
  
  belongs_to :debtor, :class_name => "User", :foreign_key => "to_user_id"
  belongs_to :creditor, :class_name => "User", :foreign_key => "from_user_id"
  
  
  validates :value, :presence => true
  validates :from_user_id, :presence => true
  validates :to_user_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name
  
  has_many :debts, :class_name => "Transaction", :foreign_key => "to_user_id"
  has_many :credits, :class_name => "Transaction", :foreign_key => "from_user_id"
  
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end
  
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end
  
  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(params[:transaction])
    # check if users named in transaction exist, if not create new ones
    @transaction.creditor = verify_user(params[:name][:from_user])
    @transaction.debtor = verify_user(params[:name][:to_user])
              
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # helper function that creates a new user if User model doesn't recognize the names
  def verify_user(name)
    user = User.find_by_name(name)
    if user.nil?
      user = User.create(name: name)
    else
      user
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BillBadger</title>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag 'blueprint/screen', media: 'screen'%>
  <%= stylesheet_link_tag 'blueprint/print', media: 'print'%>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie'%><![endif]-->
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class ="container">
    <header>
      <%= image_tag("logo.png", alt: "Bill Badger logo", class: "round") %>
      <nav class="round left">
        <ul>
         <li><%= link_to "My bills", '#' %></li>
          <li><%= link_to "My account", '#' %></li>
        </ul>
      </nav>
      
      <nav class="round right">
        <ul>
          <li><%= link_to "About", '#' %></li>
          <li><%= link_to "Halp!", '#' %></li>
          <li><%= link_to "Sign in", '#' %></li>
        </ul>
      </nav>
      
    </header>
    <section class="round">
    <%= yield %>
    </section>
  </div>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>About Bill Badger</h1>
<p>Bill Badger likes you and he is the nicest badger you'll ever meet. Bill Badger gives a shit.</p>
<p>Bill Badger's parents are <a href="http://www.github.com/jessho">Jess Ho</a> and <a href="http://www.github.com/gogwilt">Cai GoGwilt</a>. 

app/views/static_pages/home.html.erb
<h1>Home page for Bill Badger</h1>
<p>
  This is the home page for the Bill Badger web app. Sign up now and badgerize your bills.
</p>

<%= link_to "Sign up now!", "#", class: "signup_button round"%>
<p>
  Visit the <%= link_to "about", "/static_pages/about" %> page to learn more.
</p>
<p>
  This page was last updated Jan 27, 2012
</p>

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br />
    $<%= f.number_field :value %>
  </div>
  
  <%= fields_for :name do |n|%>
  <div class="field">
    <%= n.label :from_user %><br />
    <%= n.text_field :from_user %>
  </div>
  <div class="field">
    <%= n.label :to_user %><br />
    <%= n.text_field :to_user %>
  </div>
  <% end %>
  
  <div class="actions">
    <%= f.submit "Badgerize this bill"%>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <tr>
    <th>Value</th>
    <th>From user</th>
    <th>To user</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td>$<%= transaction.value %></td>
    <td><%= link_to transaction.creditor.name, transaction.creditor %></td>
    <td><%= link_to transaction.debtor.name, transaction.debtor %></td>
    <td><%= link_to 'Show', transaction %></td>
    <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
    <td><%= link_to 'Destroy', transaction, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  $<%= @transaction.value %>
</p>

<p>
  <b>From user:</b>
  <%= link_to @transaction.creditor.name, @transaction.creditor %>
</p>

<p>
  <b>To user:</b>
  <%= link_to @transaction.debtor.name, @transaction.debtor %>
</p>


<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>These are my credits:</b>
  <% @user.credits.each do |c| %>
  <br/><%= c.debtor.name %> owes me $<%= c.value %>
  <% end %>
</p>

<p>
  <b>These are my debts:</b>
  <% @user.debts.each do |d| %>
  <br/>I owe <%= d.creditor.name %> $<%= d.value %>
  <% end %>
</p>

<%= link_to 'Add a bill', new_transaction_path %> |
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>